# Generated by Django 6.1.1 on 2026-09-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_turf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('time', models.TimeField(editable=False, null=True)),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turf.turfbooking')),
            ],
        ),
    ]
