# Generated by Django 6.1.1 on 2026-10-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_turf', '0001_initial'),
        ('bookings', '0002_alter_turfbooking_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurfBooking',
            new_name='Booking',
        ),
    ]
