# Generated by Django 6.1.1 on 2026-10-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='booking_time',
        ),
    ]
