# Generated by Django 6.1.1 on 2026-10-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_v2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingv2',
            old_name='time',
            new_name='booking_time',
        ),
    ]
